name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      # see for options: https://docs.getpelican.com/en/stable/tips.html#publishing-to-github-pages-using-a-custom-github-actions-workflow
      settings: "publishconf.py"
      requirements: "pelican[markdown] typogrify micawber"
